name: 'Git Commit and Push'
description: 'Commit changes and push to repository (useful for GitOps workflows)'
author: 'irulast'

inputs:
  message:
    description: 'Commit message'
    required: true
  files:
    description: 'Files to add (space-separated, or "." for all)'
    required: false
    default: '.'
  author-name:
    description: 'Git author name'
    required: false
    default: 'GitHub Actions'
  author-email:
    description: 'Git author email'
    required: false
    default: 'actions@github.com'
  branch:
    description: 'Branch to push to (leave empty for current branch)'
    required: false
    default: ''
  force:
    description: 'Force push'
    required: false
    default: 'false'
  skip-if-empty:
    description: 'Skip commit if no changes'
    required: false
    default: 'true'

outputs:
  committed:
    description: 'Whether a commit was made'
    value: ${{ steps.commit.outputs.committed }}
  sha:
    description: 'Commit SHA (if committed)'
    value: ${{ steps.commit.outputs.sha }}

runs:
  using: 'composite'
  steps:
    - name: Configure git
      shell: bash
      run: |
        git config user.name "${{ inputs.author-name }}"
        git config user.email "${{ inputs.author-email }}"

    - name: Add and commit
      id: commit
      shell: bash
      run: |
        # Add files
        git add ${{ inputs.files }}

        # Check for changes
        if git diff --cached --quiet; then
          echo "No changes to commit"
          if [ "${{ inputs.skip-if-empty }}" = "true" ]; then
            echo "committed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
        fi

        # Commit
        git commit -m "${{ inputs.message }}"
        echo "committed=true" >> $GITHUB_OUTPUT
        echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Push with rebase retry
      if: steps.commit.outputs.committed == 'true'
      shell: bash
      run: |
        BRANCH="${{ inputs.branch }}"
        if [ -z "$BRANCH" ]; then
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
        fi

        FORCE_FLAG=""
        if [ "${{ inputs.force }}" = "true" ]; then
          FORCE_FLAG="--force"
        fi

        MAX_RETRIES=3
        RETRY_COUNT=0

        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          if git push origin "$BRANCH" $FORCE_FLAG 2>&1; then
            echo "Push successful"
            exit 0
          fi

          RETRY_COUNT=$((RETRY_COUNT + 1))
          echo "Push failed (attempt $RETRY_COUNT of $MAX_RETRIES)"

          if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
            echo "Max retries reached, failing"
            exit 1
          fi

          # Fetch latest changes
          git fetch origin "$BRANCH"

          # Check commits between our base and remote HEAD
          LOCAL_BASE=$(git rev-parse HEAD~1)
          REMOTE_HEAD=$(git rev-parse origin/"$BRANCH")

          # Get commits we need to rebase over
          NEW_COMMITS=$(git log --oneline "$LOCAL_BASE".."$REMOTE_HEAD" 2>/dev/null || echo "")

          if [ -z "$NEW_COMMITS" ]; then
            echo "No new commits to rebase over, retrying push..."
            sleep 2
            continue
          fi

          echo "New commits since our base:"
          echo "$NEW_COMMITS"

          # Check if ALL new commits are version bump commits
          # Pattern: commits containing "[skip ci]" or "bump version" (case insensitive)
          ALL_VERSION_BUMPS=true
          while IFS= read -r commit_line; do
            if [ -z "$commit_line" ]; then
              continue
            fi
            COMMIT_SHA=$(echo "$commit_line" | awk '{print $1}')
            COMMIT_MSG=$(git log -1 --format="%s" "$COMMIT_SHA")

            # Check for version bump patterns
            if echo "$COMMIT_MSG" | grep -qiE '(\[skip ci\]|bump version|chore\(.*\): bump)'; then
              echo "  ✓ Version bump commit: $COMMIT_MSG"
            else
              echo "  ✗ Non-version-bump commit: $COMMIT_MSG"
              ALL_VERSION_BUMPS=false
              break
            fi
          done <<< "$NEW_COMMITS"

          if [ "$ALL_VERSION_BUMPS" = "true" ]; then
            echo "All intervening commits are version bumps, rebasing..."

            # Rebase our commit on top of remote
            if git rebase origin/"$BRANCH"; then
              echo "Rebase successful, retrying push..."
            else
              echo "Rebase failed, aborting"
              git rebase --abort 2>/dev/null || true
              exit 1
            fi
          else
            echo "Non-version-bump commits detected, cannot auto-rebase"
            echo "Next build will handle version bump"
            exit 1
          fi

          sleep 1
        done