name: 'Bump Version'
description: 'Bump semantic version in VERSION file and optionally sync to package.json/Cargo.toml'
author: 'irulast'

inputs:
  bump-type:
    description: 'Version bump type: major, minor, or patch'
    required: false
    default: 'patch'
  version-file:
    description: 'Path to VERSION file'
    required: false
    default: 'VERSION'
  sync-package-json:
    description: 'Path to package.json to sync (leave empty to skip)'
    required: false
    default: ''
  sync-cargo-toml:
    description: 'Glob pattern for Cargo.toml files to sync (leave empty to skip)'
    required: false
    default: ''

outputs:
  old-version:
    description: 'Previous version'
    value: ${{ steps.bump.outputs.old_version }}
  new-version:
    description: 'New version after bump'
    value: ${{ steps.bump.outputs.new_version }}

runs:
  using: 'composite'
  steps:
    - name: Bump version
      id: bump
      shell: sh
      run: |
        VERSION_FILE="${{ inputs.version-file }}"
        BUMP_TYPE="${{ inputs.bump-type }}"

        # Read current version
        if [ ! -f "$VERSION_FILE" ]; then
          echo "VERSION file not found: $VERSION_FILE"
          exit 1
        fi

        OLD_VERSION=$(cat "$VERSION_FILE" | tr -d '[:space:]')
        echo "Current version: $OLD_VERSION"
        echo "old_version=$OLD_VERSION" >> $GITHUB_OUTPUT

        # Parse version parts (POSIX-compatible)
        MAJOR=$(echo "$OLD_VERSION" | cut -d. -f1)
        MINOR=$(echo "$OLD_VERSION" | cut -d. -f2)
        PATCH=$(echo "$OLD_VERSION" | cut -d. -f3)

        # Bump based on type
        case "$BUMP_TYPE" in
          major)
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            ;;
          minor)
            MINOR=$((MINOR + 1))
            PATCH=0
            ;;
          patch)
            PATCH=$((PATCH + 1))
            ;;
          *)
            echo "Invalid bump type: $BUMP_TYPE"
            exit 1
            ;;
        esac

        NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
        echo "New version: $NEW_VERSION"
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

        # Update VERSION file
        echo "$NEW_VERSION" > "$VERSION_FILE"
        echo "Updated $VERSION_FILE"

    - name: Sync package.json
      if: inputs.sync-package-json != ''
      shell: sh
      run: |
        PACKAGE_JSON="${{ inputs.sync-package-json }}"
        NEW_VERSION="${{ steps.bump.outputs.new_version }}"

        if [ -f "$PACKAGE_JSON" ]; then
          # Use jq if available, otherwise sed
          if command -v jq > /dev/null 2>&1; then
            jq ".version = \"$NEW_VERSION\"" "$PACKAGE_JSON" > tmp.json && mv tmp.json "$PACKAGE_JSON"
          else
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" "$PACKAGE_JSON"
          fi
          echo "Updated $PACKAGE_JSON to version $NEW_VERSION"
        else
          echo "Warning: $PACKAGE_JSON not found"
        fi

    - name: Sync Cargo.toml files
      if: inputs.sync-cargo-toml != ''
      shell: sh
      run: |
        PATTERN="${{ inputs.sync-cargo-toml }}"
        NEW_VERSION="${{ steps.bump.outputs.new_version }}"

        for cargo_file in $PATTERN; do
          if [ -f "$cargo_file" ]; then
            # Update version in [package] section only
            sed -i '/^\[package\]/,/^\[/{s/^version = "[^"]*"/version = "'"$NEW_VERSION"'"/}' "$cargo_file"
            echo "Updated $cargo_file to version $NEW_VERSION"
          fi
        done