name: 'Validate Migrations'
description: 'Validate SQL migration file naming convention (Flyway format)'
author: 'irulast'

inputs:
  migrations-path:
    description: 'Path to migrations directory'
    required: false
    default: 'migrations'
  pattern:
    description: 'Expected filename pattern description'
    required: false
    default: 'V<timestamp>__<description>.sql'

runs:
  using: 'composite'
  steps:
    - name: Validate migration files
      shell: sh
      run: |
        echo "Checking migration file naming in ${{ inputs.migrations-path }}..."
        cd ${{ inputs.migrations-path }}

        error_found=0
        for file in *.sql; do
          # Skip if no sql files found
          [ "$file" = "*.sql" ] && continue

          # Check Flyway naming convention: V<14-digit-timestamp>__<description>.sql
          case "$file" in
            V[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]__*.sql)
              echo "OK: $file"
              ;;
            *)
              echo "ERROR: Invalid migration filename: $file"
              echo "Expected format: ${{ inputs.pattern }}"
              error_found=1
              ;;
          esac
        done

        if [ "$error_found" = "1" ]; then
          exit 1
        fi

        echo "All migration files follow naming convention"