name: 'Kaniko Build'
description: 'Build and push Docker images using Kaniko (daemonless, secure)'
author: 'irulast'

inputs:
  context:
    description: 'Build context path'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'
  destination:
    description: 'Image destination(s), one per line (e.g., registry.example.com/image:tag)'
    required: true
  build-args:
    description: 'Build arguments (one per line, format: KEY=VALUE)'
    required: false
    default: ''
  cache:
    description: 'Enable layer caching'
    required: false
    default: 'true'
  cache-repo:
    description: 'Cache repository (e.g., registry.example.com/cache/image)'
    required: false
    default: ''
  push:
    description: 'Push the image to registry'
    required: false
    default: 'true'
  kaniko-image:
    description: 'Kaniko executor image'
    required: false
    default: 'gcr.io/kaniko-project/executor:latest'
  extra-args:
    description: 'Additional Kaniko arguments'
    required: false
    default: ''

outputs:
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}

runs:
  using: 'composite'
  steps:
    - name: Build with Kaniko
      id: build
      shell: bash
      run: |
        # Build Kaniko arguments
        KANIKO_ARGS=""
        KANIKO_ARGS="$KANIKO_ARGS --context=${{ inputs.context }}"
        KANIKO_ARGS="$KANIKO_ARGS --dockerfile=${{ inputs.dockerfile }}"

        # Add destinations (supports multiple, one per line)
        DESTINATIONS="${{ inputs.destination }}"
        while IFS= read -r dest; do
          dest=$(echo "$dest" | tr -d '[:space:]')
          if [ -n "$dest" ]; then
            KANIKO_ARGS="$KANIKO_ARGS --destination=$dest"
          fi
        done <<< "$DESTINATIONS"

        # Add build args
        BUILD_ARGS="${{ inputs.build-args }}"
        if [ -n "$BUILD_ARGS" ]; then
          while IFS= read -r arg; do
            if [ -n "$arg" ]; then
              KANIKO_ARGS="$KANIKO_ARGS --build-arg=$arg"
            fi
          done <<< "$BUILD_ARGS"
        fi

        # Cache settings
        if [ "${{ inputs.cache }}" = "true" ]; then
          KANIKO_ARGS="$KANIKO_ARGS --cache=true"
          if [ -n "${{ inputs.cache-repo }}" ]; then
            KANIKO_ARGS="$KANIKO_ARGS --cache-repo=${{ inputs.cache-repo }}"
          fi
        fi

        # Push setting
        if [ "${{ inputs.push }}" = "false" ]; then
          KANIKO_ARGS="$KANIKO_ARGS --no-push"
        fi

        # Extra arguments
        EXTRA="${{ inputs.extra-args }}"
        if [ -n "$EXTRA" ]; then
          KANIKO_ARGS="$KANIKO_ARGS $EXTRA"
        fi

        # Output the command for debugging
        echo "Kaniko command: /kaniko/executor $KANIKO_ARGS"

        # Run Kaniko
        /kaniko/executor $KANIKO_ARGS | tee /tmp/kaniko-output.txt

        # Extract digest from output
        DIGEST=$(grep -oP 'digest: sha256:[a-f0-9]+' /tmp/kaniko-output.txt | tail -1 | cut -d: -f2-)
        echo "digest=$DIGEST" >> $GITHUB_OUTPUT